### ISSUE TITLE
Edit Account Website gives "Schema validation error"

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#141]
Steps to reproduce:

1. Click "Edit Account" in the menu that opens from my username in the top right.  I am taken to https://www.lesserwrong.com/account
2. Enter a value for website.  I have tried both "FerociousTruth.com" and "http://FerociousTruth.com"
3. Click "Submit" button

Result:
Displays error "Schema validation error"

**Comment by is8ac** [comment]
In my testing "https://www.isaacleonard.com/" gives "Schema validation error", whereas "www.isaacleonard.com" submits successfully.
"FerociousTruth.com" fails for me as well.

**Comment by hyponymous** [comment]
`http://hyponymo.us` fails with "Schema validation error". `hyponymo.us` submits successfully but then the link on my profile points to `https://www.lesserwrong.com/users/hyponymo.us`.

**Comment by Discordius** [comment]
Yep, agree. This will be "fixed" by #225
