### ISSUE TITLE
Can't edit display name

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#142]
I notice that some users have a name that is different than their username. For example, https://www.lesserwrong.com/users/benito appears as "Ben" in his user profile and as the author of posts rather than as benito.  And #32 mentions a display name.  I assume that is the same thing, but there doesn't appear to be a way to edit. It doesn't appear on the account edit page.

**Comment by Raelifin** [comment]
This is a new feature on LW2.0 and is only enabled for moderators to prevent abuse. It might be worth mentioning somewhere (perhaps on a sticky post in meta) that mods can change a person's display name.
