### ISSUE TITLE
Send Message Issues

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#143]
From a user's profile page, click "Send Message".  A dialog appears.  Issues:
1. The Submit and Cancel buttons are stacked
2. There is a field for title, but not for the actual content
3. Close button has an exclamation point.  I don't know if there are other close buttons with an exclamation point, but it looks unprofessional and doesn't fit the aesthetic of the site.
4. Clicking submit appears to have no result. Dialog not closed, send not confirmed.
![image](https://user-images.githubusercontent.com/19802624/30784110-7cccbca8-a11c-11e7-9cc0-65fc976659c4.png)

**Comment by Discordius** [comment]
Indeed the message system is horrible. See #230
