### ISSUE TITLE
Hide "publish to frontpage" checkbox on meta posts

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#145]
If you go to the meta page and create a draft post, it will then appear on your user profile.  I assume that if you published it, it would show up on the meta page.  However, there is no indication of this.  Additionally, one might want to switch a draft created from the meta area to not be meta or vice versa.

It isn't clear what "Publish to frontpage" means for a meta post.  Does that make it appear in the featured section of the meta page?

**Comment by Discordius** [comment]
Yeah, the publish to frontpage button shouldn't appear at all on meta posts. Other things should be covered by #232

**Comment by crybx** [comment]
I think this was fixed by the `!document.meta` checks in [this commit a few days ago](https://github.com/Discordius/Lesswrong2/commit/34265b02eac44a206393fb8948d7b6b0a00b2fdd).

**Comment by Raemon** [comment]
Ah, yup. Sorry I forgot to close the issue.
