### ISSUE TITLE
Can't get to comments of link post

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#147]
From my user profile https://www.lesserwrong.com/users/j_thomas_moros I have a number of link posts that show under blog posts.  I can't find anyplace to click that takes me to the comments on the post (i.e. to the LW page for the post) rather than to the link.

**Comment by FerociousTruth** [comment]
This is not confined to link posts on the user profile.  The same issue exists on the daily page.  For example, see "dojo - Bad day contingency plan" on 2017-10-02

**Comment by Discordius** [comment]
Should be fixed with latest update.
