### ISSUE TITLE
Star on profile page

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#155]
On the user profile page, there is a section showing the number of posts and comments. There is a star that shows zero.  It's not clear what the star means or how it would be increased.

**Comment by Raelifin** [comment]
That's the user's Karma score. I added a tooltip in https://github.com/Discordius/Lesswrong2/commit/36581b7285a9c53ff06087253c006021ce75a3f6

**Comment by FerociousTruth** [comment]
Shouldn't this be non-zero?  On my profile https://www.lesserwrong.com/users/j_thomas_moros it shows zero.  I get that karma may not carry over exact values from the old site, but should I get credit for the fact that I posted on the old site and it was upvoted?

**Comment by Raelifin** [comment]
Yes, it should. I'll look into it.

**Comment by Raelifin** [comment]
Nobody has a karma score on the new site. The moment you log in to your account your karma is reset. Karma scores will be ported over to the new site on launch.
