### ISSUE TITLE
Delete Post Confusing and leads to errors

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#156]
Edit a draft post.  Click delete post.  It asks for confirmation.  The first time I did this, I thought nothing happened.  The confirmation box is at the top of the window while the notice that the post has been deleted is at the bottom.  You are left on the page.  I expect that I would be taken away from the page.  Clicking "Submit" on the page after deleteing the post gives the error "`{"id":"app.document_not_found"}`"

**Comment by Discordius** [comment]
Covered by #176
