### ISSUE TITLE
Bold Body Font Weight Too Low

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#162]
The font weight of bold in the body of posts is too low.  It doesn't show up as clear distinct enough from standard text.  If you notice it at all it just seems something is messed up rather than appearing intentional.  For example, the first sentence of this paragraph from [Nobody does the thing that they are supposedly doing](https://www.lesserwrong.com/posts/8iAJ9QsST9X9nzfFy/nobody-does-the-thing-that-they-are-supposedly-doing) is in bold:
![image](https://user-images.githubusercontent.com/19802624/30839535-951ac582-a240-11e7-8d13-5c713f039be5.png)

Note: this is related to #163 about the body text font.

**Comment by Discordius** [comment]
Huh, this is weird. The bold font-style is much more recognizable on my machine: 

![screen shot 2017-09-27 at 2 24 36 pm](https://user-images.githubusercontent.com/9090789/30938666-ad7c1608-a38f-11e7-90f2-cff12e846704.png)

**Comment by Discordius** [comment]
What machine are you using?

**Comment by FerociousTruth** [comment]
I'm using Chrome 61.0.3163.100 on Windows 7 Service Pack 1.  There does seem to be a significant difference in font rendering.  I'm surprised at the difference because they should be the same based on the same font.  See my comparison below at 200%

![image](https://user-images.githubusercontent.com/19802624/30972862-bc90d872-a439-11e7-8d26-a4150a6e1d5d.png)

**Comment by Raemon** [comment]
It's recognizeable on my machine but I still think upping the weight would
be preferable

**Comment by Discordius** [comment]
Covered by #227
