### ISSUE TITLE
Select a better Body Text Font

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#163]
It is generally recommended that sans-serif fonts be used for text presented on screens, however, I think the use of a serif font fits well with the "bookish" style of the site.  Currently, it seems all the text appears in the "ET Book" (at least in Chrome on windows).  This font looks fine for headings and slightly larger sizes like in links.  The 19.2px main body text, 16px comment text and the 14px description text for posts don't look very good though.  I think the problem is the variability in the thickness of the strokes of the letters.  At small sizes, the mapping to pixels accentuates the differences.  It produces an uneven feeling to the text.  See sample below.

Note that in the "Beta - First Impressions" post, user philh commented on the font saying "I'm finding the font reasonably unpleasant in some vague way. I know this was hashed out in the strategic overview thread, but datapoint. (Firefox, OS X.) I think this is more true in comments than top-level posts."

![image](https://user-images.githubusercontent.com/19802624/30839910-84371606-a242-11e7-991b-839f4117d69e.png)

**Comment by Discordius** [comment]
This appears to actually be a browser compatibility issue, or maybe an OS issue? Not sure. Also referenced in #162. The font is much more readable on my machine. I can imagine this being a windows/mac problem, and I don't have any windows machines around to test.

**Comment by FerociousTruth** [comment]
Stumbled across another good example of how the font looks on my machine (still Chrome on windows) in the comments of [this post](https://www.lesserwrong.com/posts/BEtzRE2M5m9YEAQpX/there-s-no-fire-alarm-for-artificial-general-intelligence#comments).

![image](https://user-images.githubusercontent.com/19802624/31749272-ee6c1ad8-b446-11e7-9a8d-57de791047c0.png)

In particular, note how the lowercase 'w's appear too big relative to the rest of the word and how the top of the 't' in the italicized word 'right' is week and make the 't' appear short.

**Comment by Discordius** [comment]
Should be covered by #227
