### ISSUE TITLE
Make comment permalink clearer

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#164]
Sometimes it is very useful to be able to link directly to a specific comment.  I don't see any way to get a link to a specific comment.  Perhaps a menu item in the comment's menu saying "Comment Link" or "Copy Link" would be a good way to provide access to comment links.

**Comment by Discordius** [comment]
The time links to the comment. Though I agree that this should be made clearer

**Comment by Raemon** [comment]
Updated title
