### ISSUE TITLE
Stronger branding

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#165]
NancyLebovitz commented on the "Beta - First Impressions" post that "I'm fine with the font with the serifs, but I found myself really wanting some indication of what site I was on. A little color, a border, something. This place is less distinctive than a mainstream news site."

While the overall appearance of the site is very good, it could use a stronger brand.  Something that users will feel that indeed they are on LessWrong.com  I recommend consulting a graphic designer, they may come up with better suggestions.  However, I might try creating a strong logo for use in the top menu as the "LESSWRONG" site name.  I would consider making it something that pins to the top of the browser window when you scroll down so that it stays visible and provides access to the menu at all times.

**Comment by Discordius** [comment]
Agree that we need a logo. Less agree that the current page doesn't have it's own identity. I actually feel quite happy with the brand the current typography and minimalism creates, but do think that we want to add a tiny bit of uniqueness and distinction into a few more places.

**Comment by Discordius** [comment]
Covered by #229
