### ISSUE TITLE
Ctrl-Z in post editor treats movement as edit

### ISSUE THREAD

**Issue by jkopczyn** [Discordius/Lesswrong2#174]
To reproduce:
Create a post and write something.
Edit a line.
Use the arrow keys to move the cursor elsewhere.
Ctrl-Z to undo the edit.

Expected:
The first press of Ctrl-Z undoes the last edit.

Actual:
The first press of Ctrl-Z moves the cursor to a previous position. Repeatedly pressing it eventually undoes the edit.

**Comment by Discordius** [comment]
Alas, this is something we can't easily fix without switching editor frameworks. I made a new issue on the ory-editor git: https://github.com/ory/editor/issues/484

**Comment by jkopczyn** [comment]
If they can't fix it promptly, this is worth switching.

On Oct 19, 2017 4:17 PM, "Discordius" <notifications@github.com> wrote:

Alas, this is something we can't easily fix without switching editor
frameworks. I made a new issue on the ory-editor git: ory/editor#484
<https://github.com/ory/editor/issues/484>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Discordius/Lesswrong2/issues/174#issuecomment-338063894>,
or mute the thread

**Comment by Discordius** [comment]
I think you might be underestimating the horribleness of editor frameworks, but agree that it would be a reasonably strong argument.
