### ISSUE TITLE
RSS Feed for Meta Posts

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#179]
There doesn't appear to be an RSS feed for meta posts and they don't seem to be showing up in the main feed at https://www.lesserwrong.com/feed.xml  For example, I don't see the post "Speed & Performance is our current top priority"

**Comment by Raelifin** [comment]
https://www.lesserwrong.com/feed.xml?view=meta

**Comment by Raelifin** [comment]
More transparency and exposing endpoints is a good idea, and is on my https://github.com/Discordius/Lesswrong2/tree/full-rss branch waiting for @Discordius to review, style, and extend.
