### ISSUE TITLE
Incorrect Date on Post brought in from RSS feed?

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#182]
Scott's post [It Was You Who Made My Blue Eyes Blue](https://www.lesserwrong.com/posts/qaHHJ3kkCQS4nsoGJ/it-was-you-who-made-my-blue-eyes-blue) says it was created on Sep 2, 2017 even though the [original post](http://slatestarcodex.com/2015/10/15/it-was-you-who-made-my-blue-eyes-blue/) on Scott's site is dated Oct 15, 2015.  This is very confusing.  I'm assuming this is a bug with the RSS import, unless Scott copy/pasted this post into LessWrong.

**Comment by Discordius** [comment]
Fixed that one, though they are probably more. We definitely want to do a proper pass over the core collections before November 1st.
