### ISSUE TITLE
Lack of markup view in editor makes editing content offline problematic

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#183]
Since the comment and post editor has no markup editing view, it isn't possible to compose posts and comments offline.  For example, the old site mostly followed markdown so it was possible to compose offline with a markdown preview and know that it would probably match when posted.

**Comment by Discordius** [comment]
Yeah, this is a deeper problem with WYSIWYG, but there isn't super much we can do about it. I think the benefit of WYSIWYG is worth it, though in #226 I've also considered adding a markdown mode for comments. 

Closed for now, since if we fix it, it will be fixed with #226.
