### ISSUE TITLE
The 'report a bug' chatbot causes a very annoying UI bug

### ISSUE THREAD

**Issue by angelinahli** [Discordius/Lesswrong2#184]
This happens: https://gyazo.com/00fc4452096c863e4127efb05bb23971
It is very distracting, and does not go away until I've read the 'report a message' bug. It means I cannot focus on working in another tab. Please make it stop. (I understand it might not be LW v.2.0's fault, it might just be Intercom, but it's so deeply annoying.)

**Comment by Discordius** [comment]
Agree with this. I have pinged Intercom support about turning this off, but they said it isn't possible. 

For now we are adding a setting on your profile page to deactivate Intercom, which will at least help the people who are most annoyed by it. Though I really wish we could just prevent Intercom from hijacking the tab title.

**Comment by gmarmstrong** [comment]
In the mean time, if you use [uBlock Origin](https://github.com/gorhill/uBlock), you can go to its dashboard, select the "My filters" tab, and add this line:

     www.lesserwrong.com##.intercom-launcher-frame

**Comment by Discordius** [comment]
You can now also deactivate Intercom on your user profile (top right corner and click "Edit Profile).
