### ISSUE TITLE
Link Post Pages Don't Link

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#186]
If you can get around #147 by say following a link to the page from an RSS reader, then the actual link of the link post is not on the page anwhere.  For example, [Happiness Is Not A Coherent Concept](https://www.lesserwrong.com/posts/59rvzXPjAMFkFHXoe/happiness-is-not-a-coherent-concept) is a link post to http://particularvirtue.blogspot.com/2017/08/happiness-is-not-coherent-concept.html but there is no link there from the page.

**Comment by gwillen** [comment]
Came here to report the same issue.

Also, even though #147 is closed, the click-target to get to the comments page on linkposts is still non-obvious (I believe it's just the tiny square with the comment count in it?)

I know this goes against modern web design orthodoxy, but I think it would improve usability to have a link clearly labelled with the word 'comments' that goes to the comments (and conversely a clearly-labelled link of some kind, perhaps 'article', from the comments page to the article. Although linking the article title would probably be enough.)
