### ISSUE TITLE
Frontpage images are not served over https

### ISSUE THREAD

**Issue by Discordius** [Discordius/Lesswrong2#202]
We moved the frontpage images off imgur, but apparently they are still not loaded over https. We should fix that. Probably just a flag in the react-cloudinary `Image` components somewhere.

**Comment by henryaj** [comment]
This took a surprising amount of digging... but yes, looks like you can set [`secure: true`](https://github.com/cloudinary/pkg-cloudinary-core/blob/9e7aaf7fcc7f1ecd2163461251b3a1559a04183f/cloudinary-core.js#L1779).
