### ISSUE TITLE
Comment cannot be submitted on mobile

### ISSUE THREAD

**Issue by Ezra** [Discordius/Lesswrong2#204]
Comment submit button is fully obscured by edit toolbar (found using Samsung Internet on Samsung Galaxy S8)

**Comment by Ezra** [comment]
Posts otoh can be submitted, perhaps because their submit button is higher on the page.

**Comment by Ezra** [comment]
Workaround: when you're ready to submit, switch the phone to landscape mode. The editor is even less usable in landscape (the text area can be fully obscured), but the Submit button is reachable.

**Comment by Ezra** [comment]
User AndHisHorse reports a possibly more convenient workaround of tapping above the editor to dismiss it, granting access to the submit button.

**Comment by Discordius** [comment]
Should be a bit better now, but should in the long-term be covered by #226
