### ISSUE TITLE
Editor behaves erratically on mobile

### ISSUE THREAD

**Issue by Ezra** [Discordius/Lesswrong2#205]
On mobile, the editor does weird stuff like aborting keyboard traces in the middle, mysteriously overwriting text, or appearing to delete text without deleting it from the version eventually published. Trace abort seems to happen roughly one second after entry of previous word.

Could conceivably relate to erratic cursor behavior in issue #25.

Found with both Swype Keyboard and Samsung Keyboard, in Samsung Internet on Samsung Galaxy S8.

**Comment by Ezra** [comment]
User AndHisHorse reports losing all progress approximately every two characters.
https://www.lesserwrong.com/posts/tsKF5MPgkF27nNiw2/initial-thoughts-on-assisted-formatting-of-discussion-posts/PtKXaW97eCssvyBo8

**Comment by Discordius** [comment]
Covered by #226
