### ISSUE TITLE
Unknown error when creating user account

### ISSUE THREAD

**Issue by jecneps** [Discordius/Lesswrong2#208]
I'm trying to create a new account and it's tossing up "unknown error". I'm fairly sure it's because I was trying to make a new account, but I was using an email that was still connected to an old lw account. I used a different email and it worked fine, no error.

**Comment by andrewxstewart** [comment]
I continue to get an 'Unknown error' on attempting to log in with my LW 1.0 account.

![screenshot 2017-10-20 16 52 45](https://user-images.githubusercontent.com/5137405/31845680-4a649910-b5b8-11e7-91bb-13f30ff6ebdc.png)

I can log in to LW 1.0 with that password no problem.

If I try to sign up again, I am told my email address is already in use. If I use another email, I am informed that that username is already in use.

Is there something users need to to do to trigger migration of old accounts?

**Comment by Discordius** [comment]
Yeah, you need to request a "forgot password" email

**Comment by andrewxstewart** [comment]
Cool - that worked.

Perhaps that 'Unknown Error' at login could be a plain text error for everyone, saying something like:

'Login error. LW 1.0 users can request a password here via 'Forgot Password''

**Comment by henryaj** [comment]
This seems to be fixed now.
