### ISSUE TITLE
Some people just don't see the link underlines

### ISSUE THREAD

**Issue by Discordius** [Discordius/Lesswrong2#216]
Alas, looks like my fancy link-underline implementation was a bit too ambitious, and some people just don't see the link underlines. I checked in with Ruby who had this issue, and while had had basically the exact same setup I had (latest OSX with latest Chrome), he had a bug while I didn't. So it seems to be more complicated to debug. I take this as a sign that we just in general want to move towards a less ambitious link underline solution :(

**Comment by henryaj** [comment]
Had a look at the site OS X Chrome and Safari, and can't see the issue with link underlining (looks identical in both browsers to my eye).
