### ISSUE TITLE
Comments not loading for specific post

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#240]
On only this specific post, the comments section just shows the loading animation and never loads.  Page is [Contra double crux](https://www.lesserwrong.com/posts/nm6XuC9CzNBrthpPB/contra-double-crux)

**Comment by yump** [comment]
Also affects [this post](https://www.lesserwrong.com/posts/bXavjKSzxXKYmmx4C/postmodernism-for-rationalists#comments).  I made [a dupe](https://github.com/Discordius/Lesswrong2/issues/248) before noticing this bug, and have since closed it.

**Comment by Discordius** [comment]
Appears to be fixed now, with the new editor and everything.
