### ISSUE TITLE
"Internal server error" upon password reset attempt

### ISSUE THREAD

**Issue by LunarTulip** [Discordius/Lesswrong2#254]
I just made my first attempt at logging into LW 2.0, and after some trial and error realized that I would need to reset my password from LW 1. So I attempted to do so, using the email associated with my LW 1 account. Rather than getting a password reset, I got the following error:

![lw2ise](https://user-images.githubusercontent.com/12496016/32139060-6094afd0-bbf4-11e7-9a37-c9f1845198cb.png)

I don't know much about what's causing the error, but I'm pretty sure it's not a problem with my browser, because the same error occurred both in Firefox and in Chrome.

**Comment by Discordius** [comment]
We fixed a bunch of bugs related to this, so I think it should be fixed. Happy to reopen if it's still an issue.
