### ISSUE TITLE
Constant page refresh

### ISSUE THREAD

**Issue by Pengux1** [Discordius/Lesswrong2#263]
[This](https://www.lesserwrong.com/posts/wmEcNP3KFEGPZaFJk/the-craft-and-the-community-a-post-mortem-and-resurrection) article refreshes about every minute, going back to the top of the page. This was in both Firefox and Opera.

**Comment by danluu** [comment]
Likewise in Brave and Safari on iOS and FF on Linux.

**Comment by Discordius** [comment]
Alas, sorry for that. Must have caused quite some few bad experiences. 

I've fixed on the latest push.
