### ISSUE TITLE
Markdown in Comments not working

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#264]
The comment box says "Write here (we support Markdown!"  however no markdown seems to be working.  You can see this on my [draft post](https://www.lesserwrong.com/posts/xhtFjkwvyBsCM8uRM/change-from-link-post#comments) assuming you can access one of my drafts.  This was reported by Regex on his [comment](https://www.lesserwrong.com/posts/wmEcNP3KFEGPZaFJk/the-craft-and-the-community-a-post-mortem-and-resurrection/Svgt3jAC5vqaMs67u#Svgt3jAC5vqaMs67u).

**Comment by Discordius** [comment]
Nope, totally works. Just press space after you type markdown syntax.
