### ISSUE TITLE
“(read more)” for recent comments doesn't look great when it's split up by a line break

### ISSUE THREAD

**Issue by malob** [Discordius/Lesswrong2#274]
Here's an example:
<img width="993" alt="screen shot 2017-11-08 at 20 40 38" src="https://user-images.githubusercontent.com/2914269/32633812-df40b0d2-c55d-11e7-997e-de4444a597d7.png">

Adding a non-breakinp space, `(read&nbsp;more)`, seem like an improvement to me.

<img width="951" alt="screen shot 2017-11-09 at 14 57 59" src="https://user-images.githubusercontent.com/2914269/32634003-95ce3d88-c55e-11e7-9375-f731de807f13.png">

**Comment by Discordius** [comment]
Huh, the second thing seems slightly worse to me, but I guess tastes vary. But it does improve the clickability of read-more, so I think this change makes sense.

**Comment by Raemon** [comment]
huh, I think I may have "fixed" this awhile ago by tweaking the length of the comment-excerpts such that this just doesn't come up anymore.
