### ISSUE TITLE
Link Error on 'Start Reading' Button

### ISSUE THREAD

**Issue by Fillyosopher** [Discordius/Lesswrong2#276]
The main page for the Rationality: A-Z reading has a 'Start Reading' button which links to the wrong location.
Page with error: [https://www.lesserwrong.com/rationality](https://www.lesserwrong.com/rationality)
Link goes to: [https://www.lesserwrong.com/null/preface](https://www.lesserwrong.com/null/preface)
What I assume is the correct link: [https://www.lesserwrong.com/rationality/preface](https://www.lesserwrong.com/rationality/preface)

**Comment by Discordius** [comment]
Just fixed this!
