### ISSUE TITLE
I can't see whether I upvoted posts on the In Eq sequence page

### ISSUE THREAD

**Issue by malob** [Discordius/Lesswrong2#282]
I've upvoted many, if not all, of the posts in the In Eq sequence. However, as you can see in the image below, the normal indication of this, the upvote arrow being colored green, is not showing up on the sequence page:
![screen shot 2017-11-13 at 08 44 54](https://user-images.githubusercontent.com/2914269/32737517-278fac5a-c84f-11e7-8302-0163fade709e.png)

This may be an issue with all sequence pages, I haven't checked.

**Comment by Discordius** [comment]
Fixed!
