### ISSUE TITLE
Markdown editor introduces spaces before stop.

### ISSUE THREAD

**Issue by vluzko** [Discordius/Lesswrong2#284]
The editor will convert `*words to italicize*.` -> "_words to italicize_ ." i.e. it replaces the second "*" with a space rather than an empty string. AFAICT this only occurs if the italics are followed by a stop. The same thing happens with "__", and possibly other formatting commands.

**Comment by FerociousTruth** [comment]
I think what is happening is that before the space is added to the text content, the markdown processing is triggered, and it leaves the cursor in the wrong place.  I'm guessing it is putting the cursor at the end of the markdown syntax on the assumption that you just typed the markdown and anything after that was already there.  Then the space character is actually processed and so is inserted before the period.

**Comment by Raemon** [comment]
We've since disabled markdown parsing of italics/bold. Closing
