### ISSUE TITLE
Links not visible by default

### ISSUE THREAD

**Issue by jeffkaufman** [Discordius/Lesswrong2#289]
For example, on https://www.lesserwrong.com/posts/wmEcNP3KFEGPZaFJk/the-craft-and-the-community-a-post-mortem-and-resurrection the text:

<img width="329" alt="screen shot 2017-11-16 at 11 49 59 am" src="https://user-images.githubusercontent.com/262566/32903993-6395b0f6-cac4-11e7-854a-99b8a0f3f5e6.png">

Turns out to have a link in it, but the link isn't visible unless you happen to hover over it:

<img width="317" alt="screen shot 2017-11-16 at 11 50 04 am" src="https://user-images.githubusercontent.com/262566/32903994-63a18c28-cac4-11e7-9648-5b183b51f7c5.png">

**Comment by Discordius** [comment]
Should be fixed now! Let me know this still happens anywhere. We had some browser compatibility issues.
