### ISSUE TITLE
Messages don't work at all

### ISSUE THREAD

**Issue by Ezra** [Discordius/Lesswrong2#294]
The send message dialog looks weird, with a "Title" but no message-body area.
![send message](https://user-images.githubusercontent.com/66482/33049086-414d07f4-ce13-11e7-8932-bfaf38a96554.PNG)

The "SUBMIT" button causes the entered text to vanish, but the dialog does not close, and the intended recipient perceives no effect.

The "CLOSE!" button is surprisingly enthusiastic for a button that apparently does nothing.

I would assume that this meant messaging was just not implemented, except #4 implies that messages at one time worked.

**Comment by Ezra** [comment]
Apparently this is meant to be issue #230. That issue didn't come up on a search for "message", "messages", or "messaging". Can maybe add that to the issue to make it more searchable?

**Comment by Discordius** [comment]
Done! Will track status of this with the other issue.
