### ISSUE TITLE
Page refreshes automatically when ignored for a few hours

### ISSUE THREAD

**Issue by dankuck** [Discordius/Lesswrong2#307]
If I open a page (in this case, https://www.lesserwrong.com/posts/dhj9dhiwhq3DX6W8z/hero-licensing), then use other browser tabs for a few hours, when I return to the tab, I see the page initiate a refresh.

When it refreshes, it loads at the top of the page as mentioned in issue #295.

My browser is Opera 49.0, a Chromium variant.

**Comment by Discordius** [comment]
This should usually only happen if we push an update to the page in the period you had the page open, which is something a bit harder to avoid, since I do want all clients to have the same version of our page (to avoid invalid database operations and so on).
