### ISSUE TITLE
Post edit box is tiny, make it bigger!

### ISSUE THREAD

**Issue by gwillen** [Discordius/Lesswrong2#313]
On &lt;div class="editor content-body">, change the min-height to something bigger than 80px, or otherwise let it take up the whole screen vertically. And think about changing &lt;div class="posts-new-form"> to have a width other than 640px (I prefer "100%" but I suppose it's subjective.)

**Comment by Discordius** [comment]
It is bigger now!

**Comment by gwillen** [comment]
Thank you!
