### ISSUE TITLE
When copy-pasting from Word, strikethrough shows up in editor but not in the post

### ISSUE THREAD

**Issue by zejacobi** [Discordius/Lesswrong2#324]
See it in action [here](https://www.lesserwrong.com/posts/ijwJnK9fCKqQWRhLL/my-predictions-for-2018-and-a-template-for-yours).

I copy pasted a post draft into the editor from word. Strikethrough seemed to work just find in the editor, but when I posted it, there was no strikethrough.

Screenshots attached.

Editor
<img width="854" alt="screen shot 2018-01-02 at 9 03 54 pm" src="https://user-images.githubusercontent.com/8496595/34508904-aa5e28c4-f012-11e7-8fe2-56b6894a6f98.png">

Live
<img width="777" alt="screen shot 2018-01-02 at 9 04 13 pm" src="https://user-images.githubusercontent.com/8496595/34508907-b06568b8-f012-11e7-97dd-1348fcd0f9a5.png">

**Comment by Discordius** [comment]
Fixed!
