### ISSUE TITLE
RSS filtering by karma doesn't work

### ISSUE THREAD

**Issue by jeffkaufman** [Discordius/Lesswrong2#325]
When I click on the RSS link for the front page it invites me to choose a karma limit.  If I choose anything other than 0, however, I get an empty feed:

* https://www.lesserwrong.com/feed.xml?view=frontpage loads fine
* https://www.lesserwrong.com/feed.xml?view=frontpage&karmaThreshold=0 loads fine
* https://www.lesserwrong.com/feed.xml?view=frontpage&karmaThreshold=1 gives an empty feed

(Inviting people to chose a karma threshold here doesn't make that much sense anyway, since the frontpage is curated.)

**Comment by Discordius** [comment]
Ah, I will fix that ASAP.

**Comment by Discordius** [comment]
Fixed!
