### ISSUE TITLE
Comments appearing on wrong post when reading a sequence

### ISSUE THREAD

**Issue by nmohsin** [Discordius/Lesswrong2#361]
I ran into this bug when reading this sequence: https://www.lesserwrong.com/sequences/Xo4GmYdQ8dt8djEtJ 

I've been reading the posts in sequence on desktop, hitting the next button on each article to proceed to the next one. A comment I posted mysteriously wound up on the previous post in the sequence. (https://www.lesserwrong.com/posts/XKvH8cxTnfK6LPdRX/counting-up-vs-counting-down/Geao4tBzNWodboxAp) 

I've seen Qiaochu complain about the same thing as well in some of his comments, so it's not just me.

I suspect this problem will vanish if I refresh the page before commenting, but that's just intuition.

**Comment by Discordius** [comment]
Fixed with a recent update
