### ISSUE TITLE
Glitchy text input on Android

### ISSUE THREAD

**Issue by Gurkenglas** [Discordius/Lesswrong2#449]
On my Android 7.0 smartphone, text input into a Reply text box causes lag, letters I've input disappear most of the time when I press space, etc., to the point where I use an external app to prepare comment text before pasting it in. Switching to the Desktop version of the site on the Android doesn't help.

**Comment by Raemon** [comment]
This has now been fixed, by having Android (and iOS) devices switch to a pure markdown editor.
