### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by dtujmer** [Discordius/Lesswrong2#452]
I can't sign in on any of my devices or browsers, both Linux and Windows. Tried refreshing, tried clearing cache, didn't help. Same if I try to log in with username or email.

**Comment by Raemon** [comment]
We just pushed a change which may or may not have addressed this (changed some underlying error messaging code)

Can you try again? And if it doesn't work, specify which browsers and versions you're using?

**Comment by dtujmer** [comment]
Works now! Thanks!
