### ISSUE TITLE
Some "Continue" links are broken on the /daily page

### ISSUE THREAD

**Issue by PaulRobson** [Discordius/Lesswrong2#517]
On the /daily page, some of the (Continue, xxx more words) links are broken, but not all of them. Right now if I:

1. Click on Show Hightlight next to the "Bounds of Attention" or "Against Occam's Razor" articles
2. Scroll down to the end of the highlight and click (Continue) link

I'm sent to, for example, https://www.lesswrong.com/posts/undefined/bounds-of-attention so it looks like the post id is missing.

The "Continue to Full Post" links are correct.

**Comment by Raemon** [comment]
This should be fixed now
