### ISSUE TITLE
Very slow server response times - Time to first byte (TTFB) is > 1.5 seconds

### ISSUE THREAD

**Issue by jglamine** [Discordius/Lesswrong2#53]
From the time a user starts loading the page, it takes over 1.5 seconds before the server responds with the first byte of the HTML response.

Steps to reproduce:

* Open the network tab in chrome dev tools.
* Load lesserwrong.com
* Click on the "waterfall" next to the request for lesserwrong.com
* Observe the TTFB:

![image](https://user-images.githubusercontent.com/863251/29752502-b61fa370-8b24-11e7-945b-29b5a0702a8d.png)

My guess is this is a server configuration problem, and should be pretty easy to fix.

Is lesserwrong.com running on a development server? If so that could explain it. Or perhaps the server is in Australia or something.

In any event, you might want to aim to get TTFB down to the 10ms - 300ms range.

**Comment by Discordius** [comment]
Yeah, this is a issue I've been tracking for a while. 

This is probably the result of our Server Side Rendering setup. It takes the server roughly a second or so to render the page you are supposed to see, and then it sends that to you. The majority of that time, I think, is doing a series of database queries, in a way that isn't super optimized yet. 

Getting it down to <300ms might be a bit hard without architectural changes, but we should be able to optimize the frontpage queries to get the Server Side Rendering to complete in about ~300ms or so. We can also change the architecture to send you some HTML before the SSR starts, though that wouldn't really increase usability and only fix this metric without addressing the core issue.

**Comment by jglamine** [comment]
Hmm, that makes sense. IDK what kind of database you're using, but adding
indexes sounds like the right approach. Glad you're aware of the issue!

**Comment by Discordius** [comment]
*nods* the problem is not actually indexes but roundtrips. I.e. right now some of our queries require 5-6 roundtrips, because we iteratively resolve various fields in objects. I.e. a query might look like this: 

SequenceItemQuery -> receives `sequence` object -> server analyzes sequence object, notices `postId` field -> sends query to user Post collection to get corresponding post objects -> receives `post` object -> server analyzes post object, notices `userId` field -> sends query to User collection to get corresponding user -> etc...

Not fully sure what the best way to fix that is. We can probably change our schemas to require less fractal querying, or see whether MongoDB allows some kind of query that would allow that object to be composed on the DB side, instead of doing tons of incremental queries.

**Comment by jglamine** [comment]
Yeah, I don't know much about Mongo performance tuning, but I'm sure you'll
figure something out! For what it's worth, in my experience local (or in
data-center) database calls take have less than 1ms of overhead, so even if
you're doing 50 queries that's only 50ms of overhead. I'd look into adding
indexes first.

**Comment by Discordius** [comment]
Ah, our database is hosted in a different place than our server, which might be worth changing. We currently use [Galaxy](https://galaxy.meteor.com/) as our server platform and [Mlab](mlab.com/) as our database hosting service. We could move towards putting both of them onto the same service, I just don't know of any good service that does this, while also ensuring availability, scalability and database backups.

**Comment by jglamine** [comment]
Hmm, I don't know much about various hosting providers. Seems like moving
the servers to the same data center would give us a big win.

**Comment by jimrandomh** [comment]
I think having the site and database in separate datacenters is a *much* bigger problem than being limited to a single database server. I would suggest moving the database onto the web server, assuming you can do so while still having good backups. I seriously doubt that LW2 will ever need to use multiple database servers, and in the unlikely event that it does, transitioning to postgres will probably be a better move anyways.

**Comment by Discordius** [comment]
I fixed all the latency issues. Page loading speed is now primarily a function of bundle size, which we should be able to optimize soon.

**Comment by jglamine** [comment]
@Discordius - I just tested it, and time to first byte for "https://www.lesserwrong.com/" is still > 2.0 seconds.

Can you let me know what steps you did to test this? It doesn't look like it's fixed.

**Comment by Discordius** [comment]
Yeah, which is because of our SSR setup, which first executes our JavaScript server side, and then sends the HTML. Which makes the TTFB actually dependent on the time it takes to run the bundle, which is right now about 1.5s and clearly too much.

**Comment by jglamine** [comment]
Is there another issue to track this (TTFB being ~2 seconds)? As a user, I care less about the technical details of why it is slow, and more about just the fact that it's slow.

**Comment by jimrandomh** [comment]
Caveat in Chrome' s profiler when measuring load time: If you pick "reload and start profiling", the timeline it gives you starts with an *un*load, and the unload handler is slow for some reason. If you skip that bit (which isn't really relevant to the user experience), the load time (at least for the front page) is reasonable now.

**Comment by Discordius** [comment]
Hmm, I think I prefer not having issues open that are downstream to an issue to which we have a solution. The relevant issue for bundle size is #233.

**Comment by jglamine** [comment]
It sounds like we might be measuring different things. I was using the
chrome network tab to look at TTFB, not the performance waterfall tab.

I'm curious what metric you're looking at in the waterfall tab and what
value you're getting (first meaningful paint, Dom complete, Dom
interactive, ext). Maybe it also shows TTFB?

In any event thanks, I'll track that issue.
