### ISSUE TITLE
Cannot run lesswrong2 locally

### ISSUE THREAD

**Issue by jglamine** [Discordius/Lesswrong2#534]
Steps to reproduce:

1. Checkout this repo
2. npm install
3. npm start

I get the following error:
```
 Error: Could not construct a client with those parameters
W20180422-12:01:28.391(-5)? (STDERR)     at new Client (/home/james/code/lesswrong2/node_modules/intercom-client/dist/client.js:90:13)
W20180422-12:01:28.392(-5)? (STDERR)     at server.js (packages/lesswrong/lib/events/server.js:5:22)
```

It looks like it's not able to read the intercom API key from settings.json.

Can you try to reproduce this issue and let me know if you get it too?
This is using node 7.2.1 and npm 4.0.5

**Comment by movationdesign** [comment]
Have you added **your own** Intercom API key in settings.json?

**Comment by jglamine** [comment]
settings.json already has an intercom api key.

When I add a console.log statement to server.js to log the value, it comes
back as undefined

This leads me to believe that the problem is that it's not reading the
configuration file for some reason

**Comment by jglamine** [comment]
It's working now. No clue why - I didn't change anything.

Closing issue.
