### ISSUE TITLE
Improve critical-render path

### ISSUE THREAD

**Issue by jglamine** [Discordius/Lesswrong2#54]
If we decided to do this, we'll probably want to split it out into multiple issues.

From the time I start loading a page, it takes several seconds before the first render, and several more seconds after that before the page becomes interactive.

We should look into improving the critical render path. A DomInteractiveTime of 1 second seems like an achievable goal, and it's likely not worth optimizing past that point.

It goes without saying that working on performance improvements will take time away from feature development, so we need to decided whether or not it's worth it (do our users care about the difference between 1 second page loads and 7 second page loads)?

I did a bit of investigation and here's what I found:

* We're using HTTP2, which is good.

* Time to First Byte is about 1.5 seconds. I've opened an issue to improve this, as it should be easy to get a big win here.

* Investigate whether or not getting rid of our web fonts will improve performance
    * We're loading six different web fonts.
    * Fonts are render-blocking, which means that even if the page has loaded, it won't display anything until the fonts are loaded.
        * (The situation is actually a bit more complicated than this, but in general this is true)
    * We should do some profiling to see whether or not this is worth it, then we can make a decision. For what it's worth, there are some really nice font stacks we can use consisting of only fonts which are already installed on our user's machines.

* We're loading 1.8MB of JavaScript
   * Once the JavaScript loads, it takes about 4 seconds to run. These 4 seconds are render-blocking, so the user has to wait for this to finish before they can see any content.
       * 1.3 seconds of this time is spend in the DomContentLoaded event handler, so we should look there for possible improvements.
   * Have we looked into code-splitting? IE, have multiple JavaScript bundles and lazy-load them as they are needed. This could help improve the situation.

**Comment by Discordius** [comment]
> We're loading six different web fonts.

This is definitely fixable. We only use one major font, all the others are probably some random stuff leftover from older iterations, or external scripts that are importing their own fonts. (Material UI and Algolia React Instantsearch are probably the contenders here)

> Once the JavaScript loads, it takes about 4 seconds to run. These 4 seconds are render-blocking, so the user has to wait for this to finish before they can see any content.

This shouldn't be the case. On most pages we have Server Side rendering where the user can see a non-interactive version of the page, before it gets replaced by an interactive version as soon as the javascript completes. But SSR is breaking on quite a few pages atm, though it should always render something after <2 seconds. 

> Have we looked into code-splitting? IE, have multiple JavaScript bundles and lazy-load them as they are needed. This could help improve the situation.

Yeah, the big problem here is Meteor, which is just this big dependency, and doesn't do super well on code-splitting, I think. The platform (Vulcan.js) we are using is slowly moving away from Meteor, but it might take another 6 months until we can get rid of that.

**Comment by jglamine** [comment]
Cool. If you get a chance you might want to record a page load under
Chrome's performance tab. It takes screenshots so you can see what it looks
like at different points on the time line.

If I get a chance I'll take a look again and see whether or not the
Javascript is blocking the initial render.

**Comment by jglamine** [comment]
Oh yeah, you might want to use Chrome's CPU throttling option while
developing if your aren't already. I've had issues in the past where
everything looks great on my Super powered work computer, but issues are
really noticeable on slow phones.

**Comment by Discordius** [comment]
> Oh yeah, you might want to use Chrome's CPU throttling option while
developing if your aren't already.

Oh, yeah. That sounds like a good idea. I haven't experimented with that super much.

**Comment by Discordius** [comment]
I think this is now mostly acceptable, though still not great. Closing this issue for now, though faster rendering and performance is still an issue.
