### ISSUE TITLE
Consider removing Tufte web font

### ISSUE THREAD

**Issue by jglamine** [Discordius/Lesswrong2#55]
The Tufte web font is render-blocking.

I did some performance testing using Chrome dev tools. It appears that no text is drawn until right after Tufte has finished loading.

On my (fast) connection, this adds about 200ms of delay.
When emulating a good 4g connection, this adds about 700ms of delay.

Consider switching to a font stack which uses system fonts. I'm not a huge fan of web fonts because of the performance implications, but some people really like them. Close this issue if you want to keep Tufte.

**Comment by jglamine** [comment]
This issue was created based on #54

**Comment by Discordius** [comment]
This is covered by #227
