### ISSUE TITLE
Lesserwrong links should redirect to lesswrong

### ISSUE THREAD

**Issue by ghabs** [Discordius/Lesswrong2#557]
Since the domain migration lesserwrong.com links don't resolve to lesswrong. This breaks links people have posted around the web.

Suggestion: Set up 301 redirects from lesserwrong to lesswrong.

**Comment by Raemon** [comment]
I think I may have just successfully fixed this – let me know if you're running into more issues with it.

**Comment by Raemon** [comment]
AFAICT this is now working. Closing, but let me know if there are furher issues.
