### ISSUE TITLE
Card boarders flash in and then fade-out during initial page load

### ISSUE THREAD

**Issue by jglamine** [Discordius/Lesswrong2#56]
This issue was split off from #54 

When loading the home-page, the boarders around the cards are initially shown, then they flash out. This happens even when JavaScript is disabled.

My best guess is it's either caused by a CSS animation (the server-rendered Card components have some inline transition styles), or by additional CSS which is not render blocking (I haven't been able to find any).

Anyways, I'm opening this issue in the hopes that someone who knows the code better can find it quickly.

**Comment by Discordius** [comment]
This should no longer be the case. I think.
