### ISSUE TITLE
Contact Github support to make this repo not a fork

### ISSUE THREAD

**Issue by trishume** [Discordius/Lesswrong2#80]
Github forks should only stay forks if they someday intend to merge back into the original. You can make this repository not a fork by contacting Github Support, see [here](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork).

Keeping this repo as a fork has a number of unfortunate effects:

- The Github interface will keep showing how much you've diverged, and will suggest pull requests go to the parent.
- Contributors will not get credit on their profile pages.
- People will look at the header and think they might not be looking at the main repo.

cc @Discordius I think this is something only you can do

**Comment by Discordius** [comment]
Ah, I was trying to figure out how to do that for a bit, but didn't find an obvious way. I guess contacting Github support is the way to go. Will do so ASAP.

**Comment by Discordius** [comment]
Cool, sent in a support request. Should be fixed in the next few hours.
