### ISSUE TITLE
RSS feed doesn't include formatting

### ISSUE THREAD

**Issue by trishume** [Discordius/Lesswrong2#83]
The RSS feed at https://www.lesserwrong.com/feed.xml doesn't include formatting. This makes posts like [this one](https://www.lesserwrong.com/feed.xml) pretty much unreadable. At the very least paragraph breaks and links should be included.

I'm a big fan of RSS and the existence of good RSS feeds for things drastically increases the probability I will follow them.

**Comment by Discordius** [comment]
Huh, I didn't even know we were generating any valid rss feeds at all :P 

Yeah, making RSS work was high on my doc. I am actually pleasantly surprised of how much it is actually working, after having given it half an hour of work some weeks ago.
