### ISSUE TITLE
Performance: Remove render-blocking JavaScript

### ISSUE THREAD

**Issue by jglamine** [Discordius/Lesswrong2#85]
If you have JavaScript at the top of your page, the browser isn't allowed to display anything until after it has finished downloading your JavaScript files.

Ideally, you should make it so that the page will render once the HTML and CSS are done loading, without having to wait for JavaScript. This is worth doing even if you don't have server-side rendering set up. If you do have server-side rendering set up, render-blocking JavaScript makes it so that nobody ever sees the server-rendered content.

There are a few ways to fix this. For details, see: https://developers.google.com/speed/docs/insights/BlockingJS

The offending files are:
```
https://widget.cloudinary.com/global/all.js
https://www.lesserwrong.com/…8e5f0e6100439.js?meteor_js_resource=true
```

Discovered using: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.lesserwrong.com%2F&tab=desktop

**Comment by Discordius** [comment]
This should now be fixed, if I am not horribly confused. I am definitely seeing the HTML render before the full javascript package loads, so I am not sure about the second link (which is the link to the complete javascript package).
