### ISSUE TITLE
Switch to initials-only avatars for messages

### ISSUE THREAD

**Issue by ckamm** [Discordius/Lesswrong2#87]
If I understand the README correctly, you're looking for a way to have all avatars be initial-based. I've looked at what would need to be done for that.

Avatar urls seem to be computed by `vulcan-users/lib/avatar.js` and then displayed by `vulcan-base-components/lib/users/UsersAvatar.jsx`

The `fallbackType` "initials" sets the option that gravatar returns 404 if there's no image. Probably this is supposed to make the React component switch to the initials if the image can't be found. That didn't work for me.

Unfortunately there's no option combination to force initials to be used always. (a function-valued `customImageProperty` comes close, but since the code doesn't distinguish between no-url and empty-url, that's not sufficient)

I'd suggest doing `Users.avatar.getUrl = function (user) { return ''; }` to just disable avatar urls entirely, thereby switching to initials.

**Comment by Discordius** [comment]
This should be covered by #230
